### ISSUE TITLE
slider in a tab

### ISSUE THREAD

**Issue by ghost** [metafizzy/flickity-docs#11] opened 2015-05-18 12:25 UTC
im tryng to put 2 slider in 2 different tabs.
the first tab works fine but if i click the second one the slides are all at left:0. 
if i try to resize the win it works again.
any suggestion?

on open tab
![screenshot 2015-05-18 14 52 55](https://cloud.githubusercontent.com/assets/3602866/7681145/97b0b984-fd6d-11e4-97b9-b32b9ba082da.png)

after resize win
![screenshot 2015-05-18 14 54 09](https://cloud.githubusercontent.com/assets/3602866/7681157/c0c8b7e0-fd6d-11e4-8903-03eba05999bb.png)

**Comment by desandro** [comment] 2015-06-02 20:43
Thanks for reporting this issue. I'm closing this one as a duplicate of metafizzy/flickity#65. See solution there!

**Closed as completed by desandro** 2015-06-02 20:43 UTC
Labels: duplicate
